# Basic colors
foreground              #e7e0e8
background              #151218
selection_foreground    #352d40
selection_background    #cfc1da

# Cursor colors
cursor                  #d8bafb
cursor_text_color       #3c255a

# URL underline color when hovering with mouse
url_color               #f2b7c1

# Kitty window border colors
active_border_color     #d8bafb
inactive_border_color   #4a454e
bell_border_color       #ffb4ab

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #3c255a
active_tab_background   #d8bafb
inactive_tab_foreground #ccc4cf
inactive_tab_background #4a454e
tab_bar_background      #151218

# Colors for marks
mark1_foreground #3c255a
mark1_background #d8bafb
mark2_foreground #352d40
mark2_background #cfc1da
mark3_foreground #4b252d
mark3_background #f2b7c1

# The 16 terminal colors
# black
color0 #151218
color8 #4a454e

# red
color1 #ffb4ab
color9 #ffb4ab

# green
color2  #d8bafb
color10 #d8bafb

# yellow
color3  #f2b7c1
color11 #f2b7c1

# blue
color4  #cfc1da
color12 #cfc1da

# magenta
color5  #eedcff
color13 #eedcff

# cyan
color6  #ffd9de
color14 #ffd9de

# white
color7  #e7e0e8
color15 #e7e0e8
