# Basic colors
foreground              #f1dedd
background              #1a1111
selection_foreground    #442928
selection_background    #e7bdba

# Cursor colors
cursor                  #ffb3af
cursor_text_color       #571d1d

# URL underline color when hovering with mouse
url_color               #e2c28c

# Kitty window border colors
active_border_color     #ffb3af
inactive_border_color   #534342
bell_border_color       #ffb4ab

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #571d1d
active_tab_background   #ffb3af
inactive_tab_foreground #d8c1c0
inactive_tab_background #534342
tab_bar_background      #1a1111

# Colors for marks
mark1_foreground #571d1d
mark1_background #ffb3af
mark2_foreground #442928
mark2_background #e7bdba
mark3_foreground #402d05
mark3_background #e2c28c

# The 16 terminal colors
# black
color0 #1a1111
color8 #534342

# red
color1 #ffb4ab
color9 #ffb4ab

# green
color2  #ffb3af
color10 #ffb3af

# yellow
color3  #e2c28c
color11 #e2c28c

# blue
color4  #e7bdba
color12 #e7bdba

# magenta
color5  #ffdad7
color13 #ffdad7

# cyan
color6  #ffdea8
color14 #ffdea8

# white
color7  #f1dedd
color15 #f1dedd
