# Basic colors
foreground              #f1dfdc
background              #1a1110
selection_foreground    #442925
selection_background    #e7bdb6

# Cursor colors
cursor                  #ffb4a8
cursor_text_color       #561e16

# URL underline color when hovering with mouse
url_color               #dec48c

# Kitty window border colors
active_border_color     #ffb4a8
inactive_border_color   #534341
bell_border_color       #ffb4ab

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #561e16
active_tab_background   #ffb4a8
inactive_tab_foreground #d8c2be
inactive_tab_background #534341
tab_bar_background      #1a1110

# Colors for marks
mark1_foreground #561e16
mark1_background #ffb4a8
mark2_foreground #442925
mark2_background #e7bdb6
mark3_foreground #3e2e04
mark3_background #dec48c

# The 16 terminal colors
# black
color0 #1a1110
color8 #534341

# red
color1 #ffb4ab
color9 #ffb4ab

# green
color2  #ffb4a8
color10 #ffb4a8

# yellow
color3  #dec48c
color11 #dec48c

# blue
color4  #e7bdb6
color12 #e7bdb6

# magenta
color5  #ffdad4
color13 #ffdad4

# cyan
color6  #fbdfa6
color14 #fbdfa6

# white
color7  #f1dfdc
color15 #f1dfdc
